version: "3.3"
services:
  api-ecosonar:
    build: ./EcoSonar-API
    container_name: ecosonar_api
    ports:
      - "3000:3000"
    networks:
      - sonarnet
    restart: unless-stopped

  sonar:
    image: sonarqube:lts-community
    container_name: ecosonar_sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - db
      - api-ecosonar
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    volumes:
      - ./EcoSonar-SonarQube/target/ecosonar-3.2.jar:/opt/sonarqube/extensions/plugins/ecosonar-3.2.jar:ro
      - ./EcoSonar-SonarQube/ecocode/ecocode-java-plugin-1.2.1.jar:/opt/sonarqube/extensions/plugins/ecosonar-java-plugin-1.2.1.jar:ro
      - ./EcoSonar-SonarQube/ecocode/ecocode-php-plugin-1.2.1.jar:/opt/sonarqube/extensions/plugins/ecosonar-php-plugin-1.2.1.jar:ro
      - ./EcoSonar-SonarQube/ecocode/ecocode-python-plugin-1.2.1.jar:/opt/sonarqube/extensions/plugins/ecosonar-python-plugin-1.2.1.jar:ro
      - "extensions:/opt/sonarqube/extensions"
      - "logs:/opt/sonarqube/logs"
      - "data:/opt/sonarqube/data"
    restart: unless-stopped

  db:
    image: postgres:alpine
    container_name: ecosonar_postgresql
    networks:
      - sonarnet
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: pg_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

networks:
  sonarnet:
    driver: bridge

volumes:
  data:
  logs:
  extensions:
  pg_data:
