version: "3.3"
services:
  api-ecosonar:
    build: ./EcoSonar-API
    container_name: ecosonar_api
    ports:
      - "3000:3000"
    networks:
      - sonarnet

  sonar:
    image: sonarqube:9.9-community
    container_name: ecosonar_sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - db
      - api-ecosonar
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    volumes:
      - type: bind
        source: ./EcoSonar-SonarQube/target/ecosonar-3.1-SNAPSHOT.jar
        target: /opt/sonarqube/extensions/plugins/ecosonar-3.1-SNAPSHOT.jar
      - "extensions:/opt/sonarqube/extensions"
      - "logs:/opt/sonarqube/logs"
      - "data:/opt/sonarqube/data"

  db:
    image: postgres:12
    container_name: ecosonar_postgresql
    networks:
      - sonarnet
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: pg_data:/var/lib/postgresql/data/pgdata

networks:
  sonarnet:
    driver: bridge

volumes:
  data:
  logs:
  extensions:
  pg_data:
